export const listFilm = [
  {
    maPhim: 8181,
    tenPhim: "Vacation With Friends ",
    biDanh: "vacation-with-friends",
    trailer: "https://www.youtube.com/watch?v=8YjFbMbfXaQ",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/vacation-friends_gp01.jpg",
    moTa: "A couple meets up with another couple while on vacation in USA, but their friendship takes an awkward turn when they get back home.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-06T00:40:30.583",
    danhGia: 3,
    hot: false,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8205,
    tenPhim: "Cá sấu tử thần 2",
    biDanh: "ca-sau-tu-than-2",
    trailer: "https://www.youtube.com/embed/H6MLJG0RdDE",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/ca-sau-tu-than-2_gp01.jpg",
    moTa: "Cặp đôi Eric và Jennifer đã thuyết phục Yolanda, Viktor và Cash cùng nhau lên đường khám phá hệ thống hang động xa xôi, bí ẩn, chưa được biết đến nằm sâu trong khu rừng ở phía Bắc Australia. Trên đường đi, một cơn bão nhiệt đới bất ngờ đến, họ đành phải tìm kiếm trỗ trú ẩn.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-06T01:32:11.913",
    danhGia: 8,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8225,
    tenPhim: "The Boss Baby: Back in Business – Season 3",
    biDanh: "the-boss-baby-back-in-business-–-season-3",
    trailer: "aPu6yQ0OrG8",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/the-boss-baby-back-in-business-–-season-3_gp01.jpg",
    moTa: "With a little help from his brother and accomplice, Tim, Boss Baby tries to balance family life with his job at Baby Corp headquarters !!!",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-06T01:21:57.173",
    danhGia: 6,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8233,
    tenPhim: "Conan Movie",
    biDanh: "conan-movie",
    trailer: "https://youtu.be/HSow7Ep6l_4",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/detective-conan-scarlet-bullet-tham-tu-lung-danh-conan-vien-dan-do_gp01.png",
    moTa: 'Nhật Bản đang tổ chức lễ kỷ niệm World Sports Games (WSG), sự kiện thể thao lớn nhất thế giới tại Tokyo. "Shinkansen", con tàu siêu dẫn ống chân không đầu tiên trên thế giới được chế tạo từ công nghệ mới nhất của Nhật Bản sẽ được mở chạy và có thời gian trùng với thời khắc khai mạc WSG. Con tàu được thiết lập chạy từ Ga Shin Nagoya đến Ga Tokyo với tốc độ 1000km/h. Tuy nhiên, một sự cố kỳ lạ đã diễn ra trong bữa tiệc của các nhà tài trợ nổi tiếng, theo sau đó chính là hàng loạt vụ bắt cóc các giám đốc điều hành. Conan đã liên kết vụ này về vụ án bắt cóc hàng loạt liên quan đến WSG vào 15 năm trước ở Boston.',
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-24T23:02:28.46",
    danhGia: 8,
    hot: false,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8236,
    tenPhim: "Upppp!",
    biDanh: "upppp-",
    trailer: "https://www.youtube.com/watch?reload=9&v=HWEW_qTLSEE",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/up-_gp01.jpg",
    moTa: "Carl, an old widower, goes off on an adventure in his flying house in search of Paradise Falls, his wife's dream destination.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-06T01:36:05.55",
    danhGia: 7,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8244,
    tenPhim: "Squid Game ",
    biDanh: "squid-game",
    trailer: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/squid-game_gp01.jpg",
    moTa: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-06T02:09:46.027",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8301,
    tenPhim: "Đạo mộ bút ký: Trùng Khởi ",
    biDanh: "dao-mo-but-ky-trung-khoi",
    trailer: "https://www.youtube.com/embed/t9GO1RPnDi4",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/dao-mo-but-ky-trung-khoi_gp01.jpg",
    moTa: "Trùng khởi là hậu truyện của Đạo Mộ Bút Ký kể về Ngô Tà và bí ẩn việc nghe sấm mà đội khảo cổ chú Ba của Ngô Tà khảo sát. Bí ẩn được ",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-10-14T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8370,
    tenPhim: "Canh Chim Dai Bang phan 2 ",
    biDanh: "canh-chim-dai-bang-phan-2",
    trailer: "https://www.youtube.com/embed/rudLzk6Hc_k",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/fsdfsda_gp01.jpg",
    moTa: "Canh Chim Dai Bang",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-10-11T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8373,
    tenPhim: "Siêu Trộm - Way Down (Phần 2)",
    biDanh: "sieu-trom-way-down-phan-2-",
    trailer: "https://www.youtube.com/embed/dj5xakfaKw8",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/sieu-trom-way-down_gp01.jpg",
    moTa: 'Đặc vụ Interpol xuất sắc nhưng khác thường phá vỡ luật lệ khi tập hợp bè lũ trộm cắp hòng bắt cho bằng được tên hacker mờ ám mang biệt danh "Bóng ma".',
    maNhom: "GP01",
    ngayKhoiChieu: "2021-10-11T16:56:16.397",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8569,
    tenPhim: "The lord of the ring",
    biDanh: "the-lord-of-the-ring",
    trailer: "https://www.youtube.com/embed/hEJnMQG9ev8",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/the-lord-of-the-ring_gp01.jpeg",
    moTa: 'Loki’s time has come. Watch the brand-new trailer for "Loki," and start streaming the Marvel Studios Original Series June 11 on Disney+.',
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-23T22:46:24.74",
    danhGia: 5,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8572,
    tenPhim: "red snake",
    biDanh: "red-snake",
    trailer: "https://www.youtube.com/watch?v=l265kPOsDXM",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/red-snake_gp01.jpg",
    moTa: "While trying to secure sister from Fahai's clutches, Qing winds up in a city and meets a mysterious man who can't recall his past life.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-25T00:36:13.813",
    danhGia: 5,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8573,
    tenPhim: "AVATAR2",
    biDanh: "avatar2",
    trailer: "https://www.youtube.com/watch?v=AxLH0lXEGAY",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/avatar2_gp01.jpg",
    moTa: "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora. When an ancient threat resurfaces, Jake must fight a difficult war against the humans.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-02T00:00:00",
    danhGia: 6,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8575,
    tenPhim: "red notice",
    biDanh: "red-notice",
    trailer: "https://www.youtube.com/watch?v=Pj0wz7zu3Ms",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/red-notice_gp01.jpg",
    moTa: "In the world of international crime, an Interpol agent attempts to hunt down and capture the world's most wanted art thief.",
    maNhom: "GP01",
    ngayKhoiChieu: "2022-03-10T00:00:00",
    danhGia: 9,
    hot: false,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8576,
    tenPhim: "ALIVE IN life",
    biDanh: "alive-in-life",
    trailer: "https://www.youtube.com/watch?v=jQ8CCg1tOqc",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/alive_gp01.jpg",
    moTa: "While a virus ravages a city, Joon-woo tries to stay safe by locking himself inside his apartment. Just as he loses hope, he discovers another survivor.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-01-01T00:00:00",
    danhGia: 7,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8577,
    tenPhim: "mulann",
    biDanh: "mulann",
    trailer: "https://www.youtube.com/watch?v=KK8FHdFluOQ",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/mulan_gp01.jpg",
    moTa: "A girl as a male warrior and joins the imperial army in order to prevent her sick father from being forced to enlist as he has no male heir.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-23T22:45:42.317",
    danhGia: 5,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8585,
    tenPhim: "Demon Slayer : The Mugen Train",
    biDanh: "demon-slayer-the-mugen-train",
    trailer: "https://www.youtube.com/embed/68MpiAeNqQk",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/demon-slayer-the-mugen-train_gp01.jpg",
    moTa: "Kamado Tanjiro cùng quân đoàn Diệt quỷ đi cùng với Viêm trụ Rengoku Kyōjurō để điều tra những vụ mất tích đầy bí ẩn xay ra trên một chuyến tàu. Tuy nhiên, họ không biết rằng tại đây có một cái bẫy đang chờ đón họ.  Liệu kết cục sẽ như thế nào? ",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-24T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: true,
  },
  {
    maPhim: 8586,
    tenPhim: "Onepiece Movie: Red",
    biDanh: "onepiece-movie-red",
    trailer: "https://www.youtube.com/embed/bCDtErEUamM",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/onepiece-movie-red_gp01.jpg",
    moTa: 'As revealed by the first teaser trailer, the plot will involve Shanks, whose signature scar can be seen on the "D" in the film\'s title logo. Additionally, a new female character will appear in the film, which Oda noted to be a departure from the older male characters that starred as the villains in four of the last five films. The teaser poster depicts a woman, who seems to be a sky island resident.',
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-23T22:45:35.95",
    danhGia: 10,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8635,
    tenPhim: "Spider-Man: No Way Home",
    biDanh: "spider-man-no-way-home",
    trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/spider-man-no-way-home_gp01.jpg",
    moTa: "Người Nhện không còn nhà (tên gốc tiếng Anh: Spider-Man: No Way Home) là phim siêu anh hùng năm 2021 của Hoa Kỳ và Iceland dựa trên nhân vật Peter Parker của Marvel Comics, do Columbia Pictures và Marvel Studios đồng sản xuất, và được phân phối bởi Sony Pictures Releasing. Bộ phim là phần tiếp theo của Người Nhện: Trở về nhà (2017) và Người Nhện xa nhà (2019) và là phần phim thứ 27 của Vũ trụ Điện ảnh Marvel (MCU). Bộ phim do Jon Watts đạo diễn và kịch bản được chấp bút bởi Chris McKenna và Erik Sommers. Phim có sự tham gia của Tom Holland trong vai Peter Parker cùng với Zendaya, Jacob Batalon, Marisa Tomei, Jamie Foxx, Benedict Cumberbatch và Alfred Molina.",
    maNhom: "GP01",
    ngayKhoiChieu: "2021-12-20T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: true,
  },
];

export const listBanner = [
  {
    maBanner: 1,
    maPhim: 1282,
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/ban-tay-diet-quy.png",
  },
  {
    maBanner: 2,
    maPhim: 1283,
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/lat-mat-48h.png",
  },
  {
    maBanner: 3,
    maPhim: 1284,
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/cuoc-chien-sinh-tu.png",
  },
];
